services:
  - type: worker
    name: of-agencyos-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    runtime: python3.11
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: AIRTABLE_API_KEY
        sync: false
      - key: AIRTABLE_BASE_ID
        sync: false 